name: Spinarak bot

on:
  workflow_dispatch:

jobs:
  python-selenium:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay beautifulsoup4
    - name: Remove previous screenshots
      run: |
          git config --global user.name '${{github.actor}}'
          git config --global user.email '${{github.actor}}@users.noreply.github.com'
          # Remove previous screenshots. This will force the new one to be pushed to the repo
          git rm pokemon-cafe-*.png
    - name: Run Python Selenium script
      env:
        GMAIL_SENDER: ${{ secrets.GMAIL_SENDER }}
        GMAIL_APP_PW: ${{ secrets.GMAIL_APP_PW }}
        GMAIL_RECIPIENT: ${{ secrets.GMAIL_RECIPIENT }}
        GMAIL_RECIPIENT_2: ${{ secrets.GMAIL_RECIPIENT_2 }}
      run: |
          python spinarak.py
          ls -al
    - name: Commit & push screenshot to repo
      run: |
          #git config --global user.name '${{github.actor}}'
          #git config --global user.email '${{github.actor}}@users.noreply.github.com'
          git add --all
          git commit -am "Screenshot"
          git push
